# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Measure:
      type: "object"
      required:
        - measure_name
      properties:
        measure_name:
          type: "string"
        measure_units:
          type: "string"
    Plant:
      type: "object"
      required:
        - plant_name
      properties:
        plant_name:
          type: "string"
        genus:
          type: "string"
        species:
          type: "string"
  parameters:
    measure_name:
      name: "measure_name"
      description: "Name of measure to get"
      in: path
      required: True
      schema:
        type: "string"
    plant_name:
      name: "plant_name"
      description: "Name of plant to get"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /plant:
    get:
      operationId: "plants.read_all"
      tags:
        - Plants
      summary: "Read the list of plants"
      responses:
        "200":
          description: "Successfully read plant list"
    post:
      operationId: "plants.create"
      tags:
        - Plants
      summary: "Create a plant"
      requestBody:
        description: "Plant to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "plant"
              $ref: "#/components/schemas/Plant"
      responses:
        "201":
          description: "Successfully created a plant"